from fastapi import APIRouter, Depends, status

from backend.api.routers.dependencies import get_router
from backend.api.schemas.chat import ChatRequest, ChatResponse
from backend.orchestrator.router import Router

router = APIRouter(
    prefix="/chat",
    tags=["Chat"],
)


@router.post(
    "",
    response_model=ChatResponse,
    status_code=status.HTTP_200_OK,
    summary="Process a chat request",
)
async def chat(
    request: ChatRequest,
    router_service: Router = Depends(get_router),
) -> ChatResponse:
    """
    Process a user query through the AI orchestrator.

    Args:
        request: Chat request payload.
        router_service: Application router.

    Returns:
        Final response generated by the orchestrator.
    """
    answer = router_service.route(
        prompt=request.query,
    )

    return ChatResponse(
        success=True,
        message="Request processed successfully.",
        answer=answer,
    )