from __future__ import annotations

from backend.core.config import settings
from backend.core.logging import get_logger
from backend.infrastructure.llm.chat_service import ChatService
from backend.infrastructure.llm.embedding_service import EmbeddingService
from backend.infrastructure.vector_db.qdrant_service import QdrantService
from backend.models.retrieved_chunk import RetrievedChunk
from backend.prompts.rag_prompt import RAG_SYSTEM_PROMPT

logger = get_logger(__name__)


class RAGService:
    """
    Specialist responsible for answering questions using Retrieval-Augmented
    Generation (RAG).

    This service coordinates embedding generation, vector retrieval and
    LLM response generation while delegating provider-specific operations
    to the infrastructure layer.
    """

    def __init__(
        self,
        embedding_service: EmbeddingService | None = None,
        qdrant_service: QdrantService | None = None,
        chat_service: ChatService | None = None,
    ) -> None:
        self._embedding_service = embedding_service or EmbeddingService()
        self._qdrant_service = qdrant_service or QdrantService()
        self._chat_service = chat_service or ChatService()

    def answer(
        self,
        question: str,
        limit: int = 5,
    ) -> str:
        """
        Answer a user's question using the indexed document collection.

        Args:
            question:
                User's question.

            limit:
                Maximum number of document chunks to retrieve.

        Returns:
            Grounded answer generated by the LLM.
        """

        question = question.strip()

        if not question:
            raise ValueError("Question cannot be empty.")

        logger.info("Generating embedding for RAG query.")

        query_embedding = self._embedding_service.embed_text(question)

        logger.info("Searching vector database.")

        retrieved_chunks = self._qdrant_service.search(
            collection_name=settings.qdrant_collection_name,
            query_vector=query_embedding,
            limit=limit,
        )

        if not retrieved_chunks:
            logger.info("No relevant document chunks found.")

            return (
                "No relevant information was found in the indexed documents."
            )

        logger.info(
            "Retrieved %d document chunk(s).",
            len(retrieved_chunks),
        )

        user_prompt = self._build_user_prompt(
            question=question,
            chunks=retrieved_chunks,
        )

        logger.info("Generating grounded response.")

        return self._chat_service.generate(
            model=settings.rag_model,
            system_prompt=RAG_SYSTEM_PROMPT,
            user_prompt=user_prompt,
        )

    def _build_user_prompt(
        self,
        *,
        question: str,
        chunks: list[RetrievedChunk],
    ) -> str:
        """
        Build the user prompt containing retrieved document context.

        Args:
            question:
                User's question.

            chunks:
                Retrieved document chunks.

        Returns:
            Formatted prompt passed to the LLM.
        """

        context = "\n\n--------------------\n\n".join(
            chunk.content for chunk in chunks
        )

        return (
            f"Context:\n\n"
            f"{context}\n\n"
            f"Question:\n"
            f"{question}"
        )