from pydantic import BaseModel, ConfigDict, Field

from backend.api.schemas.common import BaseResponse


class ChatRequest(BaseModel):
    """
    Chat request payload.
    """

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    query: str = Field(
        min_length=1,
        description="User query."
    )


class ChatResponse(BaseResponse):
    """
    Chat response returned by the orchestrator.
    """

    answer: str = Field(
        description="Final response generated by the orchestrator."
    )